spring:
  data:
    mongodb:
      database: ssimDB
      host: 127.0.0.1
      port: 27017
  redis:
    host: 127.0.0.1
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 6H
  http:
    encoding:
      enabled: true
      charset: UTF-8

server:
  tomcat:
    uri-encoding: UTF-8

logging:
  level:
#    root : debug
#    org.apache.http.headers: debug
#    org.apache.http.wire : debug
    org.apache.coyote.http11.Http11Processor : debug