# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
GET http://localhost:8081/task
Accept: application/json

###

GET http://localhost:8081/task/2
Accept: application/json

###

POST http://localhost:8081/task
Content-Type: application/json

{
  "termCode" : "20190",
  "profileId" : 1
}

###

POST http://localhost:8081/task/2/capturing?start
Content-Type: application/json

###

POST http://localhost:8081/task/1/capturing?resume
Content-Type: application/json

###


POST http://localhost:8081/task/1/capturing?restart
Content-Type: application/json

###

GET http://localhost:8081/task/1/bundle
Content-Type: application/json

###

POST http://localhost:8081/task/1/import?start
Content-Type: application/json

###